{% set name = "flaskwebgui" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 405b1fb23d755c17bad8f7d78017b6ac76d63841a5942d8c66dc6f7effee7d4d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - flask
    - waitress
    - whichcraft
    - psutil

test:
  imports:
    - flaskwebgui

about:
  home: https://github.com/ClimenteA/flaskwebgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create desktop applications with Flask/FastAPI/Django!
  dev_url: https://github.com/ClimenteA/flaskwebgui

extra:
  recipe-maintainers:
    - melund
